name: CatPlugin
main: org.catplugin.eu.Main
version: 1.0
api-version: 1.16
commands:
  givecustomitem:
    description: can give cannon , chickensword
    usage: /<command>
    permission: <plugin name>.basic
    permission-message:

  togglediscord:
    description: toggles discord logging
    usage: /<command>
    permission: <plugin name>.basic
    permission-message:

  craftguide:

      description: can give cannon , chickensword
      usage: /<command>

  spawnboss:
      description: spawns the boss
      usage: /<command>
      permission: <plugin name>.basic
      permission-message:

  testcmd:
    description: testentity
    usage: /<command>
    permission: <plugin name>.basic
    permission-message:
    
  getbosslocation:

    description: gives boss location
    usage: /<command>

